DROP TABLE IF EXISTS Probe CASCADE;
DROP TABLE IF EXISTS Jupiter CASCADE;
DROP TABLE IF EXISTS Surface CASCADE;
DROP TABLE IF EXISTS Image CASCADE;
DROP TABLE IF EXISTS Crew CASCADE;
DROP TABLE IF EXISTS Discovery CASCADE;